import java.awt.*;//import 
import javax.swing.*;
import java.awt.event.*;


public class JLabelDem extends JFrame implements ActionListener{ //actionlistener is a interface
    JButton b1,b2;
    JTextField jtf;//we declared 1 textfield and 2 buttons
    JLabelDem()//created constructor
    {
        
        b1= new JButton("fisrt"); //created 1 button
        b2= new JButton("second");//created 2 button
        jtf= new JTextField(20);//created textfild using JTextFild(String str, int cols)
        setLayout(new FlowLayout());//arranges the component in line ,left to rigth(in a flow) it is the default layout of applet or pane
        setSize(300,300);//size of frame is 300 by 300
        add(b1);
        add(b2);
        add(jtf);// added three components
        b1.addActionListener(this);
        b2.addActionListener(this);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    public void actionPerformed(ActionEvent e)//A semantic event which indicates that a component-defined action occurred. This high-level event is generated by a component (such as a Button) when the component-specific action occurs (such as being pressed). The event is passed to every ActionListe+ner object that registered to receive such events using the component's addActionListener method.
    {
        if(e.getSource()==b1)
            jtf.setText("First button is clicked");
        else
            jtf.setText("Second button is clicked");
            
    }
    public static void main(String args[])
    {
        new JLabelDem();
    }
}
